import ProjectWorkspacePage from '../pages/ProjectWorkspacePage';

export default function DesktopApp({
  settingsDraft,
  workspaceUi,
  projectSelection,
  chapterSelection,
  createForm,
  showRewriteInput,
  rewritePrompt,
  variants,
  variantPreview,
  editingTitle,
  editTitleValue,
  exportStatus,
  error,
  loading,
  regenerating,
  model,
  writingPrefs,
  userPrompt,
  showSettings,
  showOutline,
  outlineSaving,
  outlineError,
  desktopAiMode,
  desktopEditorContent,
  desktopSavingContent,
  desktopChapterQuery,
  debugPromptInfo,
  genProgress,
  copied,
  applyingVariant,
  readingContentRef,
  readingSectionRef,
  desktopChapters,
  filteredDesktopChapters,
  desktopCurrentChapter,
  desktopChapterNumber,
  desktopChapterWords,
  desktopTotalWords,
  desktopLastSaved,
  sortedProjects,
  enhancedPrompt,
  enhancedRewritePrompt,
  outline,
  outlineText,
  readingChapterRecord,
  onDesktopNav,
  onSelectProject,
  onReadChapter,
  onGenerate,
  onRegenerate,
  onDesktopSaveContent,
  onDesktopGenerateByMode,
  onPrepareDesktopMode,
  onOpenSettings,
  onSaveSettings,
  onLoadRewritePrompt,
  onStartEditTitle,
  onSaveTitle,
  onCancelEditTitle,
  onExport,
  onBackup,
  onRebuildIndex,
  onConfirmKeepChapter,
  onPreviewVariant,
  onDesktopApplyVariant,
  onApplyVariant,
  onGenProgressDone,
  onCopyChapter,
  onCopyFull,
  onSetRewritePrompt,
  onSetShowRewriteInput,
  onCreateProject,
  onLoadOutline,
  onSaveOutline,
  onSetOutlineText,
  onSetOutlineError,
  onSetShowOutline,
  onSetShowSettings,
  onSetModel,
  onSetWritingPrefs,
  onSetUserPrompt,
  onSetDesktopAiMode,
  onSetDesktopEditorContent,
  onSetDesktopChapterQuery,
  onSetEditTitleValue,
  onHandleLogout,
  onHandleSelectProject,
  onHandleGenerate,
  onRenameProject,
  onDeleteProject,
  onGenerateOutline,
  formatProjectUpdatedAt,
  getProjectChapterCount,
  searchQuery,
  onSearchQueryChange,
  searchResults,
  searchLoading,
  showDesktopSearch,
  onOpenDesktopSearch,
  onCloseDesktopSearch,
  onSearchResultClick,
  searchInputRef,
  onNotify,
}) {
  return (
    <ProjectWorkspacePage
      settingsDraft={settingsDraft}
      workspaceUi={workspaceUi}
      projectSelection={projectSelection}
      chapterSelection={chapterSelection}
      createForm={createForm}
      showRewriteInput={showRewriteInput}
      rewritePrompt={rewritePrompt}
      variants={variants}
      variantPreview={variantPreview}
      editingTitle={editingTitle}
      editTitleValue={editTitleValue}
      exportStatus={exportStatus}
      error={error}
      loading={loading}
      regenerating={regenerating}
      model={model}
      writingPrefs={writingPrefs}
      userPrompt={userPrompt}
      showSettings={showSettings}
      showOutline={showOutline}
      outlineSaving={outlineSaving}
      outlineError={outlineError}
      desktopAiMode={desktopAiMode}
      desktopEditorContent={desktopEditorContent}
      desktopSavingContent={desktopSavingContent}
      desktopChapterQuery={desktopChapterQuery}
      debugPromptInfo={debugPromptInfo}
      genProgress={genProgress}
      copied={copied}
      applyingVariant={applyingVariant}
      readingContentRef={readingContentRef}
      readingSectionRef={readingSectionRef}
      desktopChapters={desktopChapters}
      filteredDesktopChapters={filteredDesktopChapters}
      desktopCurrentChapter={desktopCurrentChapter}
      desktopChapterNumber={desktopChapterNumber}
      desktopChapterWords={desktopChapterWords}
      desktopTotalWords={desktopTotalWords}
      desktopLastSaved={desktopLastSaved}
      sortedProjects={sortedProjects}
      enhancedPrompt={enhancedPrompt}
      enhancedRewritePrompt={enhancedRewritePrompt}
      outline={outline}
      outlineText={outlineText}
      readingChapterRecord={readingChapterRecord}
      onDesktopNav={onDesktopNav}
      onSelectProject={onSelectProject}
      onReadChapter={onReadChapter}
      onGenerate={onGenerate}
      onRegenerate={onRegenerate}
      onDesktopSaveContent={onDesktopSaveContent}
      onDesktopGenerateByMode={onDesktopGenerateByMode}
      onPrepareDesktopMode={onPrepareDesktopMode}
      onOpenSettings={onOpenSettings}
      onSaveSettings={onSaveSettings}
      onLoadRewritePrompt={onLoadRewritePrompt}
      onStartEditTitle={onStartEditTitle}
      onSaveTitle={onSaveTitle}
      onCancelEditTitle={onCancelEditTitle}
      onExport={onExport}
      onBackup={onBackup}
      onRebuildIndex={onRebuildIndex}
      onConfirmKeepChapter={onConfirmKeepChapter}
      onPreviewVariant={onPreviewVariant}
      onDesktopApplyVariant={onDesktopApplyVariant}
      onApplyVariant={onApplyVariant}
      onGenProgressDone={onGenProgressDone}
      onCopyChapter={onCopyChapter}
      onCopyFull={onCopyFull}
      onSetRewritePrompt={onSetRewritePrompt}
      onSetShowRewriteInput={onSetShowRewriteInput}
      onCreateProject={onCreateProject}
      onLoadOutline={onLoadOutline}
      onSaveOutline={onSaveOutline}
      onSetOutlineText={onSetOutlineText}
      onSetOutlineError={onSetOutlineError}
      onSetShowOutline={onSetShowOutline}
      onSetShowSettings={onSetShowSettings}
      onSetModel={onSetModel}
      onSetWritingPrefs={onSetWritingPrefs}
      onSetUserPrompt={onSetUserPrompt}
      onSetDesktopAiMode={onSetDesktopAiMode}
      onSetDesktopEditorContent={onSetDesktopEditorContent}
      onSetDesktopChapterQuery={onSetDesktopChapterQuery}
      onSetEditTitleValue={onSetEditTitleValue}
      onHandleLogout={onHandleLogout}
      onHandleSelectProject={onHandleSelectProject}
      onHandleGenerate={onHandleGenerate}
      onRenameProject={onRenameProject}
      onDeleteProject={onDeleteProject}
      onGenerateOutline={onGenerateOutline}
      formatProjectUpdatedAt={formatProjectUpdatedAt}
      getProjectChapterCount={getProjectChapterCount}
      searchQuery={searchQuery}
      onSearchQueryChange={onSearchQueryChange}
      searchResults={searchResults}
      searchLoading={searchLoading}
      showDesktopSearch={showDesktopSearch}
      onOpenDesktopSearch={onOpenDesktopSearch}
      onCloseDesktopSearch={onCloseDesktopSearch}
      onSearchResultClick={onSearchResultClick}
      searchInputRef={searchInputRef}
      onNotify={onNotify}
    />
  );
}
