import HomePage from '../pages/HomePage';
import MobileAllProjectsPage from '../pages/mobile/MobileAllProjectsPage';
import MobileOutlinePage from '../pages/mobile/MobileOutlinePage';
import MobileProjectPage from '../pages/mobile/MobileProjectPage';
import MobileReaderEditorPage from '../pages/mobile/MobileReaderEditorPage';
import MobileSearchOverlay from '../pages/mobile/MobileSearchOverlay';
import MobileShell from '../pages/mobile/MobileShell';
import MobileWritingPage from '../pages/mobile/MobileWritingPage';

export default function MobileApp({
  // search overlay
  showMobileSearch,
  mobileSearchInputRef,
  mobileSearchQuery,
  setMobileSearchQuery,
  mobileSearchLoading,
  mobileSearchResults,
  closeMobileSearch,
  handleMobileSearchResultClick,
  // mobile view state
  mobileView,
  onBackClick,
  navigateTo,
  // writing page
  currentProject,
  mobileWritingTarget,
  mobileWritingKind,
  mobileWritingPrompt,
  handleMobileWritingPromptChange,
  model,
  setModel,
  writingPrefs,
  setWritingPrefs,
  loading,
  regenerating,
  handleMobileWritingGenerate,
  mobileWritingError,
  error,
  mobileWritingOutput,
  readingChapter,
  readingContent,
  setMobileWritingOutput,
  // outline page
  projectDetails,
  outline,
  formatOutlinePlan,
  openSettingsEditor,
  setShowOutline,
  // all projects page
  sortedProjects,
  allProjectDetails,
  getProjectIntro,
  formatProjectUpdatedAt,
  getProjectChapterCount,
  handleHomeProjectOpen,
  // reader/editor page
  settingsDraft,
  workspaceUi,
  projectSelection,
  chapterSelection,
  handleReadChapter,
  createForm,
  handleCreateProject,
  handleOpenSettings,
  showOutline,
  handleLoadOutline,
  showSettings,
  mobileWorldRef,
  mobileCharactersRef,
  mobileSummaryRef,
  enhancedPrompt,
  handleSaveSettings,
  outlineText,
  setOutlineText,
  setOutlineError,
  outlineError,
  handleSaveOutline,
  outlineSaving,
  userPrompt,
  setUserPrompt,
  handleGenerate,
  genProgress,
  handleGenProgressDone,
  readingSectionRef,
  editingTitle,
  editTitleValue,
  setEditTitleValue,
  handleSaveTitle,
  handleCancelEditTitle,
  handleStartEditTitle,
  showRewriteInput,
  setShowRewriteInput,
  setRewritePrompt,
  handleLoadRewritePrompt,
  copied,
  handleCopyChapter,
  displayContent,
  handleCopyFull,
  enhancedRewritePrompt,
  handleRegenerate,
  readingChapterRecord,
  handleConfirmKeepChapter,
  readingTheme,
  setReadingTheme,
  readingFontSize,
  setReadingFontSize,
  variantPreview,
  readingContentRef,
  handleReadingContentScroll,
  showScrollTop,
  handleScrollToTop,
  debugPromptInfo,
  handleOpenMobileWriting,
  setMobileEditTitle,
  setMobileEditContent,
  mobileEditTitle,
  mobileEditContent,
  handleMobileSaveEdit,
  mobileEditSaving,
  variants,
  handlePreviewVariant,
  handleApplyVariant,
  applyingVariant,
  // home/shelf page
  featuredProject,
  featuredChapterLabel,
  featuredUpdatedLabel,
  recentHomeProjects,
  hasHomeProjects,
  fallbackRecentProjects,
  handleOpenAllProjects,
  handleMobileQuickAction,
  openMobileSearch,
  // project page
  exportStatus,
  mobileMaterialsOpen,
  savingSettings,
  editWorld,
  editCharacters,
  editStyle,
  editSummary,
  editEditorialMemory,
  mobileChapterMenu,
  handleExport,
  handleBackup,
  handleRefresh,
  setMobileMaterialsOpen,
  setEditWorld,
  setEditCharacters,
  setEditStyle,
  setEditSummary,
  setEditEditorialMemory,
  setShowSettings,
  setMobileGenerateOpen,
  setMobileVariantsOpen,
  setMobileChapterMenu,
  handleMobileDeleteChapter,
}) {
  return (
    <>
      {showMobileSearch && (
        <MobileSearchOverlay
          inputRef={mobileSearchInputRef}
          query={mobileSearchQuery}
          onQueryChange={setMobileSearchQuery}
          loading={mobileSearchLoading}
          results={mobileSearchResults}
          onClose={closeMobileSearch}
          onResultClick={handleMobileSearchResultClick}
        />
      )}
      <MobileShell>
        {mobileView === 'writing' && (
          <MobileWritingPage
            currentProject={currentProject}
            mobileWritingTarget={mobileWritingTarget}
            mobileWritingKind={mobileWritingKind}
            mobileWritingPrompt={mobileWritingPrompt}
            onMobileWritingPromptChange={handleMobileWritingPromptChange}
            model={model}
            onSetModel={setModel}
            writingPrefs={writingPrefs}
            onSetWritingPrefs={setWritingPrefs}
            loading={loading}
            regenerating={regenerating}
            onMobileWritingGenerate={handleMobileWritingGenerate}
            mobileWritingError={mobileWritingError}
            error={error}
            mobileWritingOutput={mobileWritingOutput}
            readingChapter={readingChapter}
            readingContent={readingContent}
            navigateTo={navigateTo}
            onSetMobileWritingOutput={setMobileWritingOutput}
            onBackClick={onBackClick}
          />
        )}{mobileView === 'outline' && currentProject && (
          <MobileOutlinePage
            currentProject={currentProject}
            projectDetails={projectDetails}
            outline={outline}
            formatOutlinePlan={formatOutlinePlan}
            openSettingsEditor={openSettingsEditor}
            navigateTo={navigateTo}
            onSetShowOutline={setShowOutline}
            onBackClick={onBackClick}
          />
        )}{mobileView === 'allProjects' && (
          <MobileAllProjectsPage
            sortedProjects={sortedProjects}
            allProjectDetails={allProjectDetails}
            getProjectIntro={getProjectIntro}
            formatProjectUpdatedAt={formatProjectUpdatedAt}
            getProjectChapterCount={getProjectChapterCount}
            onHomeProjectOpen={handleHomeProjectOpen}
            onBackClick={onBackClick}
          />
        )}

        <MobileReaderEditorPage
          settingsDraft={settingsDraft}
          workspaceUi={workspaceUi}
          projectSelection={projectSelection}
          chapterSelection={chapterSelection}
          onReadChapter={handleReadChapter}
          onBackClick={onBackClick}
          createForm={createForm}
          handleCreateProject={handleCreateProject}
          handleOpenSettings={handleOpenSettings}
          showOutline={showOutline}
          setShowOutline={setShowOutline}
          handleLoadOutline={handleLoadOutline}
          showSettings={showSettings}
          mobileWorldRef={mobileWorldRef}
          mobileCharactersRef={mobileCharactersRef}
          mobileSummaryRef={mobileSummaryRef}
          enhancedPrompt={enhancedPrompt}
          handleSaveSettings={handleSaveSettings}
          outlineText={outlineText}
          setOutlineText={setOutlineText}
          setOutlineError={setOutlineError}
          outlineError={outlineError}
          handleSaveOutline={handleSaveOutline}
          outlineSaving={outlineSaving}
          userPrompt={userPrompt}
          setUserPrompt={setUserPrompt}
          model={model}
          setModel={setModel}
          writingPrefs={writingPrefs}
          setWritingPrefs={setWritingPrefs}
          handleGenerate={handleGenerate}
          loading={loading}
          regenerating={regenerating}
          genProgress={genProgress}
          handleGenProgressDone={handleGenProgressDone}
          error={error}
          readingSectionRef={readingSectionRef}
          editingTitle={editingTitle}
          editTitleValue={editTitleValue}
          setEditTitleValue={setEditTitleValue}
          handleSaveTitle={handleSaveTitle}
          handleCancelEditTitle={handleCancelEditTitle}
          handleStartEditTitle={handleStartEditTitle}
          showRewriteInput={showRewriteInput}
          setShowRewriteInput={setShowRewriteInput}
          setRewritePrompt={setRewritePrompt}
          handleLoadRewritePrompt={handleLoadRewritePrompt}
          copied={copied}
          handleCopyChapter={handleCopyChapter}
          displayContent={displayContent}
          handleCopyFull={handleCopyFull}
          enhancedRewritePrompt={enhancedRewritePrompt}
          handleRegenerate={handleRegenerate}
          readingChapterRecord={readingChapterRecord}
          handleConfirmKeepChapter={handleConfirmKeepChapter}
          readingTheme={readingTheme}
          setReadingTheme={setReadingTheme}
          readingFontSize={readingFontSize}
          setReadingFontSize={setReadingFontSize}
          variantPreview={variantPreview}
          readingContentRef={readingContentRef}
          handleReadingContentScroll={handleReadingContentScroll}
          showScrollTop={showScrollTop}
          handleScrollToTop={handleScrollToTop}
          debugPromptInfo={debugPromptInfo}
          handleOpenMobileWriting={handleOpenMobileWriting}
          setMobileEditTitle={setMobileEditTitle}
          setMobileEditContent={setMobileEditContent}
          mobileEditTitle={mobileEditTitle}
          mobileEditContent={mobileEditContent}
          handleMobileSaveEdit={handleMobileSaveEdit}
          mobileEditSaving={mobileEditSaving}
          variants={variants}
          handlePreviewVariant={handlePreviewVariant}
          handleApplyVariant={handleApplyVariant}
          applyingVariant={applyingVariant}
        />

        {/* ===== Mobile: Shelf View ===== */}
        {mobileView === 'shelf' && (
          <HomePage
            createForm={createForm}
            featuredProject={featuredProject}
            featuredChapterLabel={featuredChapterLabel}
            featuredUpdatedLabel={featuredUpdatedLabel}
            recentHomeProjects={recentHomeProjects}
            hasHomeProjects={hasHomeProjects}
            fallbackRecentProjects={fallbackRecentProjects}
            onNavigate={navigateTo}
            onHomeProjectOpen={handleHomeProjectOpen}
            onOpenAllProjects={handleOpenAllProjects}
            onMobileQuickAction={handleMobileQuickAction}
            onOpenMobileSearch={openMobileSearch}
            onCreateProject={handleCreateProject}
            formatProjectUpdatedAt={formatProjectUpdatedAt}
            getProjectChapterCount={getProjectChapterCount}
          />
        )}

        {/* ===== Mobile: Project View (chapter list) ===== */}
        {mobileView === 'project' && currentProject && (
          <MobileProjectPage
            currentProject={currentProject}
            projectDetails={projectDetails}
            readingChapter={readingChapter}
            exportStatus={exportStatus}
            mobileMaterialsOpen={mobileMaterialsOpen}
            showSettings={showSettings}
            showOutline={showOutline}
            savingSettings={savingSettings}
            editWorld={editWorld}
            editCharacters={editCharacters}
            editStyle={editStyle}
            editSummary={editSummary}
            editEditorialMemory={editEditorialMemory}
            outlineText={outlineText}
            outlineError={outlineError}
            outlineSaving={outlineSaving}
            mobileChapterMenu={mobileChapterMenu}
            mobileWorldRef={mobileWorldRef}
            mobileCharactersRef={mobileCharactersRef}
            mobileSummaryRef={mobileSummaryRef}
            onBackClick={onBackClick}
            onExport={handleExport}
            onBackup={handleBackup}
            onOpenSettings={handleOpenSettings}
            onRefresh={handleRefresh}
            onSetMobileMaterialsOpen={setMobileMaterialsOpen}
            onSetEditWorld={setEditWorld}
            onSetEditCharacters={setEditCharacters}
            onSetEditStyle={setEditStyle}
            onSetEditSummary={setEditSummary}
            onSetEditEditorialMemory={setEditEditorialMemory}
            onSaveSettings={handleSaveSettings}
            onSetShowSettings={setShowSettings}
            onSetOutlineText={setOutlineText}
            onSetOutlineError={setOutlineError}
            onSaveOutline={handleSaveOutline}
            onSetShowOutline={setShowOutline}
            onOpenMobileWriting={handleOpenMobileWriting}
            onReadChapter={handleReadChapter}
            navigateTo={navigateTo}
            onSetMobileGenerateOpen={setMobileGenerateOpen}
            onSetMobileVariantsOpen={setMobileVariantsOpen}
            onSetMobileChapterMenu={setMobileChapterMenu}
            onMobileDeleteChapter={handleMobileDeleteChapter}
          />
        )}
      </MobileShell>
    </>
  );
}
